version: "3.7"

services:
  php-fpm:
    container_name: test-rest_php-fpm
    build:
      context: ./docker/php-fpm
    volumes:
      - ./:/var/www/app
    ports:
      - "9000:9000"
    depends_on:
      - mysql
    networks:
      - backend_network

  mysql:
    container_name: test-rest_mysql
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: default
      MYSQL_DATABASE: default
      MYSQL_USER: default
      MYSQL_PASSWORD: default
    volumes:
      - ./docker/mysql/data:/var/lib/mysql:rw
      - ./:/var/www:ro
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - backend_network

networks:
  backend_network:
    driver: bridge